Repository yippee-fun/phlex, pull requests merged in 2022-09, with the labels that each got.

#140 Faster tag methods
  lib/phlex/html.rb
Labels: performance

#141 Use tr instead of gsub
  lib/phlex/component.rb
  lib/phlex/html.rb
Labels: performance

#142 Only strip javascript from links if there is javascript
  lib/phlex/component.rb
Labels: performance

#143 Faster attributes
  lib/phlex/component.rb
  lib/phlex/html.rb
Labels: performance

#160 Fix renderable class check
  lib/phlex/renderable.rb
Labels: bug

#157 Initial Compiler
  .github/workflows/ci.yml
  fixtures/compilation/vcall.rb
  fixtures/component_helper.rb
  lib/phlex.rb
  lib/phlex/compiler.rb
  lib/phlex/compiler/formatter.rb
  lib/phlex/compiler/generators/standard_element.rb
  lib/phlex/compiler/generators/void_element.rb
  lib/phlex/compiler/optimizers/vcall.rb
  lib/phlex/compiler/visitors/base.rb
  lib/phlex/compiler/visitors/component.rb
  lib/phlex/compiler/visitors/component_method.rb
  lib/phlex/compiler/visitors/file.rb
  lib/phlex/component.rb
  lib/phlex/html.rb
  phlex.gemspec
  test/phlex/compilation/vcall.rb
  test/phlex/compiler/formatter.rb
  test/phlex/component/tags.rb
Labels: compiler

#188 Rename base visitor
  lib/phlex/compiler/visitors/base_visitor.rb
  lib/phlex/compiler/visitors/component.rb
  lib/phlex/compiler/visitors/component_method.rb
  lib/phlex/compiler/visitors/file.rb
Labels: compiler

#195 Support chain appends in Compiler formatter
  lib/phlex/compiler/formatter.rb
  test/phlex/compiler/formatter.rb
Labels: compiler

#201 Add `helpers` proxy
  docs/pages/rails_integration.rb
  lib/phlex/view.rb
Labels: DSL
