Repository yippee-fun/phlex, pull requests merged in 2024-04, with the labels that each got.

#703 Lets go
  .github/workflows/ci.yml
  .rubocop.yml
  fixtures/components/say_hi.rb
  lib/phlex.rb
  lib/phlex/csv.rb
  lib/phlex/elements.rb
  lib/phlex/helpers.rb
  lib/phlex/html.rb
  lib/phlex/html/standard_elements.rb
  lib/phlex/html/void_elements.rb
  lib/phlex/kit.rb
  lib/phlex/sgml.rb
  lib/phlex/testing/view_helper.rb
  phlex.gemspec
  test/phlex/kit.rb
  test/phlex/view/capture.rb
  test/phlex/view/legacy_template_method.rb
  test/phlex/view/naughty_business.rb
Labels: breaking

#704 FIFO cache
  lib/phlex.rb
  lib/phlex/elements.rb
  lib/phlex/fifo.rb
  lib/phlex/sgml.rb
  test/phlex/view/process_attributes.rb
Labels: breaking

#705 Restore `mix` functionality when the mixed values are nil
  lib/phlex/helpers.rb
  test/phlex/view/mix.rb
Labels: backport

#714 Prefer `delete` to `tr` when using it to remove characters from a string
  lib/phlex/sgml.rb
Labels: performance
